"""Added cancel_requested and cancel_accepted to Loan table

Revision ID: a4f95be27a46
Revises: 2d317d245740
Create Date: 2024-08-05 12:43:41.678798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4f95be27a46'
down_revision: Union[str, None] = '2d317d245740'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan', sa.Column('cancel_requested', sa.Boolean(), nullable=True))
    op.add_column('loan', sa.Column('cancel_accepted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loan', 'cancel_accepted')
    op.drop_column('loan', 'cancel_requested')
    # ### end Alembic commands ###
